<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.5.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FPL.AI.Manager.Agents\FPL.AI.Manager.Agents.csproj" />
    <ProjectReference Include="..\FPL.AI.Manager.RAG\FPL.AI.Manager.RAG.csproj" />
  </ItemGroup>

</Project>
